/*
 * This source file was generated by the Gradle 'init' task
 */
package kireiiiiiiii.ttt;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void appHasAGreeting() {
        assertNotNull(" ", " "); // TODO: Tests :3
    }
}
